### ISSUE TITLE
error message: when joining server

### ISSUE THREAD

**Issue by Leude** [Timeox2k/ProxyBlockXYZ-SpigotPlugin#2]
[06:26:21 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to ProxyBlockXYZSpigot v1.2
java.lang.NullPointerException: null
        at xyz.proxyblock.spigot.listener.ConnectionListener.onLogin(ConnectionListener.java:41) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-152]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.2.jar:git-Paper-152]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-152]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-152]
        at net.minecraft.server.v1_16_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:311) ~[patched_1.16.2.jar:git-Paper-152]
        at net.minecraft.server.v1_16_R2.LoginListener$1.run(LoginListener.java:212) ~[patched_1.16.2.jar:git-Paper-152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[06:26:21 INFO]: Leude[201.175.203.158/201.175.203.158:10817] logged in with entity id 1929 at ([world]10.699999988079073, 95.0, 10.659263451161294)
[06:26:22 INFO]: [Owner] Leude entro al servidor

**Comment by HorizonCode** [comment]
should be fixed here https://github.com/Timeox2k/ProxyBlockXYZ-SpigotPlugin/compare/master...HorizonCode:master
just wait for Timeox2k to merge and push the update to Spigot
